### ISSUE TITLE
使用cocos2d-x创建的工程怎么在我的Xcode里运行？

### ISSUE THREAD

**Issue by Elaine666** [plter/eoeFlappyBird#1]
博主您好，我下了您的代码，想在我自己的Xcode运行，但是发现不能编译，应该是缺少cocos2d-x的依赖项，但是我不知道怎么添加，工程访问的cocos2d-x路径是不是还是您的工程路径？急求博主解答

**Comment by plter** [comment]
工程是使用Cocos2d-x 2开发的，把工程放在Cocos2d-x 2源码projects相应的目录下就可以了
